import { hellix } from "./fonts";
import "./globals.css";
import { WizardProvider } from "@/components/admin/WizardProvider";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "Tu menú digital",
  description: "Generated by create next app",

  // ✅ Favicons + Apple icon desde /public
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      { url: "/favicon.ico" }, // legacy fallback
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },

  // ✅ PWA manifest desde /public
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={hellix.variable}>
      <body>
        <WizardProvider>{children}</WizardProvider>
        {/* <Analytics /> */}
      </body>
    </html>
  );
}
